export const stats = [
  {
    playerName: 'Karl Anthony Towns',
    position: 'Center',
    number: '32',
    avgPts: 26.5,
    avgRbds: 10.8,
    avgAst: 4.4,
    fgPercentage: 50.8,
    threeP: 41.2,
    ft: 79.6,
    stl: 0.9,
    blk: 1.2,
    gp: 35,
    thumbnail: './assets/imgs/kat1.jpg',
  },
  {
    playerName: "D'Angelo Russell",
    position: 'Guard',
    number: '0',
    avgPts: 23.1,
    avgRbds: 3.9,
    avgAst: 6.3,
    fgPercentage: 42.6,
    threeP: 36.7,
    ft: 80.9,
    stl: 1.1,
    blk: 0.3,
    gp: 45,
  },
];
